@port = 5050
@Host =  http://localhost
@route = api/v1/auth

POST {{Host}}:{{port}}/{{route}}/register
Content-Type: application/json

{
    "username":"batis2",
    "email":"batis22@batis.com",
    "password":"12341234", 
    "isAdmin":true
}


###
POST {{Host}}:{{port}}/{{route}}/login
Content-Type: application/json

{
    "username":"batis2",
    "password":"12341234"
}

